apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e4kog4wrs-nodejs
  janus-idp.io/tekton: e4kog4wrs-nodejs
  backstage.io/kubernetes-id: e4kog4wrs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e4kog4wrs-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
